// 定义action的type
const SET_STATE_DEAFAULT: string = 'SET_STATE_DEAFAULT'
const SET_CURRENT_SUBJECT: string = 'SET_CURRENT_SUBJEC'
const SET_CURRENT_MODEL: string = 'SET_CURRENT_MODEL'
const SET_QUERY_LIST: string = 'SET_QUERY_LIST'
const SET_USER_ANSWER: string = 'SET_USER_ANSWER'

// 定义action type的类型
type SET_STATE_DEAFAULT_TYPE = typeof SET_STATE_DEAFAULT
type SET_CURRENT_SUBJECT_TYPE = typeof SET_CURRENT_SUBJECT
type SET_CURRENT_MODEL_TYPE = typeof SET_CURRENT_MODEL
type SET_QUERY_LIST_TYPE = typeof SET_QUERY_LIST
type SET_USER_ANSWER_TYPE = typeof SET_USER_ANSWER

export { SET_STATE_DEAFAULT, SET_CURRENT_SUBJECT, SET_CURRENT_MODEL, SET_QUERY_LIST, SET_USER_ANSWER }

export type {
  SET_STATE_DEAFAULT_TYPE,
  SET_CURRENT_SUBJECT_TYPE,
  SET_CURRENT_MODEL_TYPE,
  SET_QUERY_LIST_TYPE,
  SET_USER_ANSWER_TYPE,
}
