const SET_STATE_DEAFAULT: string = 'SET_STATE_DEAFAULT'
const SET_CURRENT_SUBJECT: string = 'SET_CURRENT_SUBJEC'
const SET_CURRENT_MODEL: string = 'SET_CURRENT_MODEL'

type SET_STATE_DEAFAULT_TYPE = typeof SET_STATE_DEAFAULT
type SET_CURRENT_SUBJECT_TYPE = typeof SET_CURRENT_SUBJECT
type SET_CURRENT_MODEL_TYPE = typeof SET_CURRENT_MODEL

export { SET_STATE_DEAFAULT, SET_CURRENT_SUBJECT, SET_CURRENT_MODEL }

export type { SET_STATE_DEAFAULT_TYPE, SET_CURRENT_SUBJECT_TYPE, SET_CURRENT_MODEL_TYPE }
